---
- name: Create {{ build_lib }} on {{ build_system_ip }}
  ibmi_cl_command:
    cmd: CRTLIB {{ build_lib }}
  delegate_to: "build_system"

- name: "check if ~/.netrc contains ibm i target login"
  lineinfile:
    name: ~/.netrc
    line: "machine {{build_system_ip}} login {{build_system_user}} password {{build_system_pass}}"
    state: present
  check_mode: false

- block:
    - name: Create {{ build_path }} on remote IBM i
      ansible.builtin.file:
        path: "{{ build_path }}"
        state: "directory"
      delegate_to: "build_system"

    - name: combine transfer_command
      set_fact:
        transfer_command: "scp {{ local_workspace }}/sendMsg.c {{build_system_user}}@{{build_system_ip}}:{{ build_path }}/sendMsg.c"

    - name: put STMFs to remote IBM i
      shell:
        cmd: 'sshpass -p "{{ build_system_pass }}" {{ transfer_command }}'
  when: build_with_stmfs
...